name: ocpp-server docker build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific directory
        uses: actions/checkout@v4.2.2
        with:
          repository: sbdtechs/ocpp-server
          path: ./ # This will place files in the root of the build directory

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch
          release_branch: main

      - name: "Login via Azure CLI"
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f ./Server/aks-deploy.Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/citrineos:${{ steps.version.outputs.major-version }}.${{ steps.version.outputs.minor-version }}.${{ steps.version.outputs.patch-version }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/citrineos:${{ steps.version.outputs.major-version }}.${{ steps.version.outputs.minor-version }}.${{ steps.version.outputs.patch-version }}
          docker build -f ./DirectusExtensions/aks-directus.Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/directus:${{ steps.version.outputs.major-version }}.${{ steps.version.outputs.minor-version }}.${{ steps.version.outputs.patch-version }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/directus:${{ steps.version.outputs.major-version }}.${{ steps.version.outputs.minor-version }}.${{ steps.version.outputs.patch-version }}          
